### ISSUE TITLE
[question] Using twirl for on-the-fly templates

### ISSUE THREAD

**Issue by q10** [playframework/twirl#227]
Is it currently possible to easily use Twirl as a standalone compiler?   I would like to be able to use the library to render template strings on-the-fly like the following example (think of Spring Expression Language, but for Scala):

```
val str = """
@(x: Int)
Squaring the integer returns @{x * x}
"""

val template = compiler.compile(str) // A string would always be returned

template.invoke(42) // => "Squaring the integer returns 1764"
```

However, all existing documentation appears to point to using Twirl as an sbt plugin with fixed template files stored in the resources/ directory...

**Comment by ignasi35** [comment]
Hi @q10 , Twirl compiles the templates into scala code that you can then invoke. But in order to invoke it must be loaded on your running JVM first. 

`on-the-fly` templates is not the common use case but maybe you can use Dynamic Class Loading and reflection. 

Since this is not an issue but more a discussion I'll close this issue. Feel free to continue the discussion on https://discuss.lightbend.com/
