### ISSUE TITLE
Support global variables

### ISSUE THREAD

**Issue by PromanSEW** [playframework/twirl#413]
Please add support for global template variables without ugly hacks as
```twirl
@import java.lang.Boolean; val isAdmin = Templates.isAdmin(request)
```

**Comment by PromanSEW** [comment]
Duplicate of #89

**Comment by PromanSEW** [comment]
Any news about this feature? Using template parameters is not a nice solution, if you don't want to use hacks. Just allow `@val tmp = SomeClass.meth()`, so it works with `@import` well, where is the problem? Twirl template _should be_ functiontal-oriented (like Scala) HTML without imperative variables? Please explain

**Comment by mkurz** [comment]
I think the reason this is not supported is because no one took time to implement it.
I put 
- #89
on the Play 3.1 roadmap, if time allows I can look into that, it shouldn't be really hard I guess, the parser needs to be adjusted.
@PromanSEW if you have time to look into that I would review a pull request.
